# 通用配置
spring:
  application:
    name: spring-boot-integration
  ## Thymeleaf相关配置
  thymeleaf:
    # 开发时，关闭页面缓存
    cache: false
  profiles:
    active: dev
  redis:
    # TODO 替换为自己Redis真实环境
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: localhost
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    druid:
      # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
      # spring.datasource.druid.filters=stat,wall,slf4j
      filters: stat,slf4j
      # \u521D\u59CB\u5316\u65F6\u5EFA\u7ACB\u7269\u7406\u8FDE\u63A5\u7684\u4E2A\u6570
      initial-size: 5
      # \u8FDE\u63A5\u6C60\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570\u91CF
      min-idle: 5
      # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\u91CF
      max-active: 20
      # \u83B7\u53D6\u8FDE\u63A5\u65F6\u6700\u5927\u7B49\u5F85\u65F6\u95F4
      max-wait: 60000
      # \u914D\u7F6Eaop\u8DEF\u5F84
      # TODO \u66FF\u6362\u4E3A\u81EA\u5DF1\u6240\u9700\u8981\u5207\u9762\u7684\u8DEF\u5F84
      aop-patterns: top.yangzefeng.integration.*.service.*
      # \u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filter:
        stat:
          # \u662F\u5426\u5F00\u542F\u6162sql\u67E5\u8BE2\u76D1\u63A7
          log-slow-sql: true
          # \u6162SQL\u6267\u884C\u65F6\u95F4
          slow-sql-millis: 2000
      # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      min-evictable-idle-time-millis: 300000
      # \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      time-between-eviction-runs-millis: 60000
      # \u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
      use-global-data-source-stat: true
      # \u7528\u6765\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548\u7684sql\uFF0C\u8981\u6C42\u662F\u4E00\u4E2A\u67E5\u8BE2\u8BED\u53E5
      validation-query: SELECT 'x'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: top.yangzefeng.integration.carousel.entity.Carousel
  mapper-locations: classpath*:/mapper/**/*.xml
lua:
  ratelimit:
    script:
      # 自定义lua限流接口脚本文件位置
      location: script/lua/ratelimit.lua
