# 通用配置
spring:
  application:
    name: spring-boot-integration
  # Thymeleaf相关配置
  thymeleaf:
    # 开发时，关闭页面缓存
    cache: false
  profiles:
    active: dev
  redis:
    # TODO 替换为自己Redis真实环境
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: localhost
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # spring.datasource.druid.filters=stat,wall,slf4j
      filters: stat,slf4j
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池最小空闲连接数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间
      max-wait: 60000
      # 配置aop路径
      # TODO 替换为自己真实项目路径
      aop-patterns: top.yangzefeng.integration.*.service.*
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filter:
        stat:
          # 是否开启慢sql查询监控
          log-slow-sql: true
          # 慢SQL执行时间
          slow-sql-millis: 2000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 'x'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: top.yangzefeng.integration.carousel.domain.entity.Carousel
  mapper-locations: classpath*:/mapper/**/*.xml
lua:
  ratelimit:
    script:
      # 自定义lua限流接口脚本文件位置
      location: script/lua/ratelimit.lua
